import Config

# Configure your database
config :homeschooling, Homeschooling.Repo,
  username: "postgres",
  password: "Emilly595652!",
  hostname: "localhost",
  database: "homeschooling_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :homeschooling, HomeschoolingWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "55w5zydFjhJS2AAnVS4eCJ/Za5HjlPLf7LXTGbsLVRCnertlvY6bIU+a300b5aOU",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :homeschooling, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configuração do Joken para desenvolvimento
config :homeschooling,
       :jwt_secret,
       "2CpyFS6xIcZ/Gjab6Fa1hScuLN4R02MNscSK6De3e8jgvFFexLwfZCwLF+89loP1"

# Configuração do Swoosh Mailer
config :homeschooling, Homeschooling.Mailer, adapter: Swoosh.Adapters.Local

# Configuração para pré-visualizar emails em /dev/mailbox
config :swoosh, :api_client, false
config :swoosh, :mailbox_preview, mode: :alias

config :mint,
  transport_options: [
    {:debug, {:output, :standard_io}},
    {:log_level, :debug}
  ]

config :stripity_stripe,
  api_key:
    "sk_test_51SZZbLJQV5vJKLkqZZZd2iUdmPm8IFCbQ6dGNBBSgMUnFYfEb6hAtjey2OT6VDsst1wGJkz4HE7ddQpFs7OtTRIr002ouLIb2r",
  signing_secret: "whsec_9bed91c997649e891dfb6d2431b78fcd6656e0cf676da46a3022d24334439da0"
